name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

            # - name: Set up SSH
            #   run: |
            #     mkdir -p ~/.ssh
            #     echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
            #     chmod 600 ~/.ssh/id_rsa
            #     ssh-keyscan -H 14.225.192.64 >> ~/.ssh/known_hosts

            - name: Deploy with Docker Compose
              run: |
                  ssh -o StrictHostKeyChecking=no nkeyskuo@14.225.210.241 "source ~/.nvm/nvm.sh && nvm use 20 && node -v && cd /var/www/medpulse.vn && git reset --hard && git pull && rm -rf node_modules && npm i && npm run build"